INSERT INTO public.catchments(
	catchment_id, name, service_provider)
	VALUES
(1,'Vancouver Island North','North Island Employment Foundations Society'),
(2,'Comox Valley - Powell River','Creative Employment Access Society'),
(3,'Parksville - Alberni','Central Vancouver Island Job Opportunities Building Society'),
(4,'Nanaimo','MAXIMUS Canada Employment Services Inc.'),
(5,'Cowichan Valley','ETHOS Career Management Group Ltd.'),
(6,'Langford - Sooke','WorkLink Employment Society'),
(7,'Greater Victoria','MAXIMUS Canada Employment Services Inc.'),
(8,'Saanich Peninsula - Gulf Islands','Beacon Community Services'),
(9,'Sea to Sky','Open Door Social Services Society'),
(10,'North Vancouver','Young Women''s Christian Association'),
(11,'Vancouver City Centre','Open Door Social Services Society'),
(12,'Vancouver Midtown','Pacific Community Resources Society'),
(13,'Vancouver Northeast','M.O.S.A.I.C. Multi-Lingual Orientation Service Association for Immigrant Communities'),
(14,'Vancouver South','Young Women''s Christian Association'),
(15,'Richmond','S.U.C.C.E.S.S. (formerly United Chinese Community Enrichment Services Society),'),
(16,'Maple Ridge','Douglas College'),
(17,'Tri-Cities','Young Women''s Christian Association'),
(18,'Delta','M.O.S.A.I.C. Multi-Lingual Orientation Service Association for Immigrant Communities'),
(19,'North Surrey','Options Community Services Society'),
(20,'Surrey Cloverdale','M.O.S.A.I.C. Multi-Lingual Orientation Service Association for Immigrant Communities'),
(21,'Surrey Newton','Options Community Services Society'),
(22,'South Surrey - White Rock','M.O.S.A.I.C. Multi-Lingual Orientation Service Association for Immigrant Communities'),
(23,'Langley','Douglas College'),
(24,'Burnaby','WCG International Consultants Ltd.'),
(25,'New Westminster','Fraser Works Co-operative'),
(26,'Mission','MAXIMUS Canada Employment Services Inc.'),
(27,'Abbotsford','MAXIMUS Canada Employment Services Inc.'),
(28,'Fraser Northeast','WCG International Consultants Ltd.'),
(29,'Cariboo','Horton Ventures Inc.'),
(30,'Thompson - Nicola','Community Futures Development Corporation of Thompson Country'),
(31,'Kamloops - Thompson','Open Door Social Services Society'),
(32,'Southern Okanagan','MAXIMUS Canada Employment Services Inc.'),
(33,'Central Okanagan','WCG International Consultants Ltd.'),
(34,'Shuswap - Columbia','WCG International Consultants Ltd.'),
(35,'West Kootenay - Boundary','Kootenay Career Development Society'),
(36,'Central Kootenay','Kootenay Career Development Society'),
(37,'East Kootenay','Kootenay Employment Services Society'),
(38,'North Okanagan','Community Futures Development Corporation of the North Okanagan'),
(39,'North Coast','Hecate Strait Employment Development Society'),
(40,'Northwest','Northwest Training Ltd.'),
(41,'Bulkley - Upper Skeena','Kopar Administration Ltd.'),
(42,'Lakes District','Progressive Employment Services Ltd.'),
(43,'Prince George','WCG International Consultants Ltd.'),
(44,'Northeast','Employment Connections North Corp.'),
(45,'Peace River South','Horton Ventures Inc.')