INSERT INTO centres
VALUES
(1,1,'WorkBC Centre - Campbell River'),
(2,1,'WorkBC Centre - Port Hardy'),
(3,2,'WorkBC Centre - Courtenay'),
(4,2,'WorkBC Centre - Powell River'),
(5,3,'WorkBC Centre - Port Alberni'),
(6,3,'WorkBC Centre - Ucluelet'),
(7,3,'WorkBC Centre - Tofino'),
(8,3,'WorkBC Centre - Parksville'),
(9,4,'WorkBC Centre - Nanaimo'),
(10,5,'WorkBC Centre - Duncan'),
(11,5,'WorkBC Centre - Ladysmith'),
(12,6,'WorkBC Centre - Langford'),
(13, 6,'WorkBC Centre - Sooke'),
(14,7,'WorkBC Centre - Victoria - Douglas'),
(15,7,'WorkBC Centre - Victoria - Borden'),
(16,8,'WorkBC Centre - Sidney'),
(17,8,'WorkBC Centre - Salt Spring Island'),
(18,9,'WorkBC Centre - Sechelt'),
(19,9,'WorkBC Centre - Squamish'),
(20,10,'WorkBC Centre - North Vancouver'),
(21,11,'WorkBC Centre - Vancouver - 134 East Hastings'),
(22,11,'WorkBC Centre - Vancouver - Burrard'),
(23,11,'WorkBC Centre - Vancouver - W Pender'),
(24,12,'WorkBC Centre - Vancouver - East 3rd'),
(25,12,'WorkBC Centre - Vancouver - Midtown West'),
(26,13,'WorkBC Centre - Vancouver - Commercial'),
(27,14,'WorkBC Centre - Vancouver - South'),
(28,15,'WorkBC Centre - Richmond - Granville Ave'),
(29,16,'WorkBC Centre - Maple Ridge'),
(30,17,'WorkBC Centre - Port Moody'),
(31,17,'WorkBC Centre - Coquitlam'),
(32,17,'WorkBC Centre - Port Coquitlam'),
(33,18,'WorkBC Centre - Delta - 88th'),
(34,18,'WorkBC Centre - Delta - Delta St'),
(35,19,'WorkBC Centre - Surrey - Guildford'),
(36,19,'WorkBC Centre - Surrey - Whalley'),
(37,20,'WorkBC Centre - Surrey - 56 Ave'),
(38,21,'WorkBC Centre - Surrey - Newton'),
(39,22,'WorkBC Centre - Surrey - 152 St'),
(40,23,'WorkBC Centre - Langley'),
(41,23,'WorkBC Centre - Aldergrove'),
(42,24,'WorkBC Centre - Burnaby - Metrotown'),
(43,24,'WorkBC Centre - Burnaby - Brentwood'),
(44,24,'WorkBC Centre - Burnaby - Edmonds'),
(45,25,'WorkBC Centre - New Westminster'),
(46,26,'WorkBC Centre - Mission'),
(47,27,'WorkBC Centre - Abbotsford'),
(48,28,'WorkBC Centre - Chilliwack'),
(49,28,'WorkBC Centre - Hope'),
(50,28,'WorkBC Centre - Agassiz'),
(51,29,'WorkBC Centre - Quesnel'),
(52,29,'WorkBC Centre - Williams Lake'),
(53,29,'WorkBC Centre - 100 Mile House'),
(54,29,'WorkBC Centre - Bella Coola'),
(55,30,'WorkBC Centre - Merritt'),
(56,30,'WorkBC Centre - Lillooet'),
(57,30,'WorkBC Centre - Ashcroft'),
(58,31,'WorkBC Centre - Kamloops - Lansdowne'),
(59,31,'WorkBC Centre - Clearwater'),
(60,31,'WorkBC Centre - Barriere'),
(61,31,'WorkBC Centre - Chase'),
(62,31,'WorkBC Centre - Kamloops - Tranquille'),
(63,32,'WorkBC Centre - Penticton'),
(64,32,'WorkBC Centre - Oliver'),
(65,32,'WorkBC Centre - Princeton'),
(66,32,'WorkBC Centre - Summerland'),
(67,33,'WorkBC Centre - Kelowna'),
(68,33,'WorkBC Centre - West Kelowna'),
(69,33,'WorkBC Centre - Rutland'),
(70,34,'WorkBC Centre - Salmon Arm'),
(71,34,'WorkBC Centre - Sicamous'),
(72,34,'WorkBC Centre - Golden'),
(73,34,'WorkBC Centre - Revelstoke'),
(74,35,'WorkBC Centre - Trail'),
(75,35,'WorkBC Centre - Castlegar'),
(76,35,'WorkBC Centre - Grand Forks'),
(77,36,'WorkBC Centre - Creston'),
(78,36,'WorkBC Centre - Nelson'),
(79,36,'WorkBC Centre - Nakusp'),
(80,37,'WorkBC Centre - Fernie'),
(81,37,'WorkBC Centre - Cranbrook'),
(82,37,'WorkBC Centre - Invermere'),
(83,38,'WorkBC Centre - Vernon'),
(84,38,'WorkBC Centre - Enderby'),
(85,39,'WorkBC Centre - Prince Rupert - Market'),
(86,39,'WorkBC Centre - Masset'),
(87,39,'WorkBC Centre - Queen Charlotte'),
(88,40,'WorkBC Centre - Terrace - 1st Ave'),
(89,40,'WorkBC Centre - Kitimat'),
(90,41,'WorkBC Centre - Smithers'),
(91,41,'WorkBC Centre - Hazelton'),
(92,42,'WorkBC Centre - Vanderhoof'),
(93,42,'WorkBC Centre - Fort St James'),
(94,42,'WorkBC Centre - Burns Lake'),
(95,43,'WorkBC Centre - Valemount'),
(96,43,'WorkBC Centre - Prince George'),
(97,43,'WorkBC Centre - Mackenzie'),
(98,44,'WorkBC Centre - Fort St John'),
(99,44,'WorkBC Centre - Fort Nelson'),
(100,45,'WorkBC Centre - Dawson Creek'),
(101,45,'WorkBC Centre - Chetwynd'),
(102,15,'WorkBC Centre - Richmond - No 5')